export const data: any = {
  list: [
    {
      type: 'grid',
      icon: 'icon-grid-',
      columns: [
        {
          span: 12,
          list: [
            {
              type: 'input',
              icon: 'icon-input',
              options: {
                width: '100%',
                defaultValue: '',
                required: false,
                dataType: 'string',
                pattern: '',
                placeholder: '',
                disabled: false,
                maxlength: -1,
                showWordLimit: false,
                remoteFunc: 'func_1745744745000_3613',
              },
              name: '单行文本',
              key: '1745744745000_3613',
              model: 'input_1745744745000_3613',
              rules: [{ type: 'string', message: '单行文本格式不正确' }],
            },
          ],
        },
        {
          span: 12,
          list: [
            {
              type: 'input',
              icon: 'icon-input',
              options: {
                width: '100%',
                defaultValue: '',
                required: false,
                dataType: 'string',
                pattern: '',
                placeholder: '',
                disabled: false,
                maxlength: -1,
                showWordLimit: false,
                remoteFunc: 'func_1745744746000_54065',
              },
              name: '单行文本',
              key: '1745744746000_54065',
              model: 'input_1745744746000_54065',
              rules: [],
            },
          ],
        },
      ],
      options: { gutter: 0, justify: 'start', align: 'top', remoteFunc: 'func_1745744743000_7216' },
      name: '栅格布局',
      key: '1745744743000_7216',
      model: 'grid_1745744743000_7216',
      rules: [],
    },
    {
      type: 'input',
      icon: 'icon-input',
      options: {
        width: '100%',
        defaultValue: '',
        required: false,
        dataType: 'string',
        pattern: '',
        placeholder: '',
        disabled: false,
        maxlength: -1,
        showWordLimit: false,
        remoteFunc: 'func_1745744748000_10831',
      },
      name: '单行文本',
      key: '1745744748000_10831',
      model: 'input_1745744748000_10831',
      rules: [],
    },
  ],
  config: { labelWidth: 100, labelPosition: 'right', size: 'small' },
};
